spring:
  application:
    name: aiservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitness-mirco-ai
      database: fitness-mirco-ai
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8083
